= *Conclusion*

This final chapter looks back at the project as a whole and summarizes what has been built, what was learned during the process, and what remains to be done in future iterations of the work. The goal of the project, as set out in Chapter 1, was to deliver a cross-platform medication tracking application aimed specifically at elderly users and the caregivers who support them, with an emphasis on clarity of the interface, privacy of the stored data, and a simple installation story that does not require an external server. The work carried out over the past two semesters has produced a working desktop application that meets the core of those goals.

== Summary of Work Done

The project began with a survey of the existing medication tracking applications on the market, including Apple Health, Medisafe, MyTherapy, EveryDose, Round Health and Dosecast. Each was analyzed against a set of criteria such as price, platform availability, accessibility, customizability, and support for caregiver roles. The conclusion of that analysis, presented in Chapter 2, was that none of the existing applications combined a strong focus on elderly accessibility, a clear caregiver workflow, local-only data storage, and a free, open-source distribution model. This finding shaped the requirements and use cases that drove the remainder of the project.

Building on those requirements, Chapter 3 presented the system design. A normalized database schema covering users, patients, caregivers, medications, schedules, logs and supporting tables was specified using an entity-relationship model. A user-interface design tailored to elderly users with larger interactive elements, increased contrast and a simplified navigation structure was sketched, and the development tools that the project would rely on, Go, Wails, Svelte, Git and GitHub, were introduced and justified.

Chapter 4 then described the application as it was actually built. The implementation realizes the planned architecture as a single Go module that embeds a Svelte single-page application through the Wails framework and persists its data into a local SQLite file through the GORM object-relational mapper. The application supports three roles — administrator, patient and caregiver — each with its own navigation and set of permitted actions. Patients can sign in, see today's adherence at a glance on the dashboard, and consult a four-level (daily, weekly, monthly, yearly) schedule view in which they can mark each individual dose as taken or skipped. Caregivers can link themselves to patients by email, assign new medication schedules through a form that integrates a built-in drug database lookup, and edit or remove existing schedules at any time. Authorization is enforced on the Go side of every entry point so that the rules cannot be bypassed by editing the frontend.

The engineering side of the project is equally important. The source code is hosted in a public GitHub repository, where every piece of work was first captured as an issue, developed on a dedicated branch, opened as a pull request, automatically built by a GitHub Actions workflow, reviewed by another team member and only then merged into `main`. A second workflow uses a build matrix to produce signed binaries for Linux, macOS and Windows whenever a version tag is pushed, which made it possible to publish four official releases (`v0.0.1`, `v0.0.2`, `v0.0.3` and the current `v0.5.0`) without anyone compiling the binaries by hand. The resulting binaries are also remarkably compact: each of the three platform builds in `v0.5.0` fits in less than 14 MB (approximately 11 MB on Linux, 14 MB on Windows and only 4 MB on macOS), which is an order of magnitude smaller than the equivalent Electron-based desktop applications that dominate the category and is a direct consequence of choosing the lightweight Wails runtime over heavier alternatives. Over the course of the project the team produced 110 commits, opened and closed 33 issues, and merged 34 pull requests across four contributors.

== Lessons Learned

Several practical lessons came out of the project. The first was the value of insisting on a pull-request based workflow even for a small team: catching build breakages on the pull request rather than on `main` removed an entire class of "it works on my machine" interruptions and kept the main branch always usable. The second was that capturing every piece of work as a GitHub issue before writing any code for it turned otherwise informal conversations between team members into a permanent, searchable record that could later be linked from the corresponding commit and pull request.

== Future Work

The application as delivered covers the core of medication tracking for patients and caregivers, but a number of features that were originally listed in the requirements could not be completed within the available time. The two largest of these are described below, together with several smaller improvements that would round out the application.

=== Notification and Reminder System

The most significant feature that has been left for future work is the *notification and reminder system*. The requirements in Chapter 2 describe an intelligent reminder mechanism that would alert the patient before each scheduled dose, escalate to a louder or longer alert if the dose is not acknowledged, and optionally inform the linked caregiver after a configurable grace period. The schema already provides for this: the `Notification` table records the schedule, the type (voice or text), the time at which the notification was sent, and whether it has been read. What has not yet been implemented is the background process that wakes up at the planned dose times, raises the system-level notification through the operating system, plays the chosen reminder sound, and records the resulting `Notification` row. Adding this layer would require either a small scheduler inside the Wails background runtime or, on platforms that support it, integration with the operating system's own notification scheduler so that reminders continue to fire even when the application window is closed. The system also needs to handle the situation where the computer is powered off at the planned dose time, by replaying any missed reminders the next time the application starts.

=== Internationalization and Right-to-Left Support

The second large piece of unfinished work is *internationalization*. The application was always intended to support Arabic as well as English, with full right-to-left text and layout, but the current implementation ships with English-only strings hard-coded into the Svelte components. Adding internationalization would consist of three steps: extracting every user-visible string into a translation catalog, introducing a small store that holds the currently selected language together with a `t(key)` helper that the components import, and adding the `dir="rtl"` attribute and the necessary CSS adjustments so that the layout mirrors correctly when Arabic is selected. The translations themselves are within reach because the team are native Arabic speakers, but the mechanical work of refactoring every page to read its strings from the catalog did not fit into the schedule. A later iteration would also need to handle locale-specific date and number formatting, and to provide an Arabic version of the welcome and help texts.

=== Other Improvements

In addition to the two large items above, several smaller improvements have been identified as candidates for future iterations:

- *Drug-interaction warnings.* The current drug database supports a search by trade name and scientific name but does not yet check whether a newly added medication interacts with one of the patient's existing prescriptions. Adding this check would re-use the same database that already powers the autocomplete, together with a small interactions table populated from a public source.
- *PDF reporting.* The system could generate a printable PDF summary of a patient's adherence over a chosen period, which the patient could then take to a follow-up consultation with their doctor.
- *Health measurement logging.* The `Measurement` table is part of the schema but the user interface to record vital signs such as blood pressure or glucose has not yet been built.
- *Refill reminders.* The schedule already records a quantity per dose; deriving an estimated refill date from the remaining stock and warning the caregiver in advance would be a small but useful addition.

== Final Remarks

Despite the items left for future work, the project has met its primary goal of producing a functional, cross-platform medication tracking application that respects the privacy of its users and is genuinely usable by the elderly people for whom it was designed. The combination of a Go backend, a Svelte frontend, GORM-backed local storage and a GitHub-driven development workflow has proven to be a productive and maintainable foundation, and the unfinished features described above can all be added on top of the architecture as it stands. The team hopes that the work documented in this report will serve both as a working application and as a starting point for the further improvements that have been outlined here.

The complete source code of the project, together with the full history of issues, pull requests and releases that is described in Chapter 4, is publicly available at #text(fill: blue)[#link("https://github.com/nashamri/pills")[`github.com/nashamri/pills`]]. Readers who want to inspect the implementation in more detail, download a pre-built binary for Windows, macOS or Linux, or contribute improvements of their own are encouraged to visit the repository directly.
