// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateUser(arg1:main.UserDTO):Promise<main.UserDTO>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetAllUsers():Promise<Array<main.UserDTO>>;

export function GetUser(arg1:number):Promise<main.UserDTO>;

export function Greet(arg1:string):Promise<string>;

export function UpdateUser(arg1:main.UserDTO):Promise<main.UserDTO>;
