// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:main.UserRole):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetUsers():Promise<Array<main.User>>;

export function Login(arg1:string,arg2:string):Promise<main.User>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:main.UserRole):Promise<void>;
